version: '3'
services:
  postgresdb:
    container_name: postgres
    image: postgres:16
    env_file:
      - .env
    volumes:
      - "./data/pg:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file:
      - .env
    volumes:
      - "./data/pgadmin/:/var/lib/pgadmin:rw"
    ports: 
      - "8080:80"


  